import Head from "next/head"
import Layout, { siteTitle } from "../components/Layout/Layout"
import Hero from "../components/Hero/Hero"
import About from "../components/About/About"
import Skills from "../components/Skills/Skills"

const Home = () => {
  return (
    <Layout>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <Hero />
      <About />
      <Skills />
    </Layout>
  )
}

export default Home
