import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Layout, { siteTitle } from "../components/Layout"
import Hero from "../components/Hero"
import About from "../components/About"

const Home = () => {
  return (
    <Layout>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <About />
    </Layout>
  )
}

export default Home
